<?php

return [
    'paragraph1' => 'In the current realities of the development of decentralized solutions, more and more WEB3 applications are gradually appearing. Including messengers.',
    'paragraph2' => 'When analyzing the solutions available on the market, it becomes clear that all modern messengers based on blockchain technology have a problem with speed and smooth operation, as well as the lack of functions and user experience familiar to users of centralized messengers.',
    'paragraph3' => 'The above-mentioned problems of modern decentralized messengers lead to the fact that they lack a user audience. Customers who download blockchain messengers for the first time, without seeing the usual functionality in them and without getting the usual user experience, immediately become disappointed and decide to delete or simply not use such an inconvenient application.',
    'paragraph4' => 'At the moment, the choice of decentralized messengers is quite limited. And they all have significant drawbacks. For example, charges for messages, an insufficiently friendly interface, and slow operation speed.',
    'paragraph5' => 'Also, all of them are united by the lack of any serious user base. At the moment, the most popular such clients are barely crossing the threshold of 100,000 downloads in app stores. This is precisely the result of the fact that, based on a blockchain with existing problems, it is difficult to create dApps that can adequately compete with centralized counterparts, such as Telegram with instant speed, bots, big data and a very friendly and smooth interface, which has already led to more than 900 million users. And first of all, the problem is the speed of operation of decentralized solutions compared to centralized ones.',
    'paragraph6' => 'In existing blockchain networks, with their speed of about 10 thousand. With TPS and substantial fees (for organizing data transfer in messengers), messengers, if they are popular enough, either do not work fast enough or require payment of commissions.',
    'paragraph7' => 'The solution to this problem has pushed a messenger to the masses, which could be both convenient at the level of centralized solutions and would provide people with absolutely safe personal, confidential or intimate communication.',
    'paragraph8' => 'For the base, Telegram was chosen as the usual centralized messenger, as one of the safest, most popular and fastest growing centralized messengers in the world.',
    'paragraph9' => 'The interface of this messenger is quite friendly, intuitive and has a pleasant smoothness and speed.',
    'paragraph10' => 'The functionality is very extensive and allows you to create bots that solve a lot of tasks for both ordinary and business users.',
    'paragraph11' => 'The messenger has functionality that allows you to launch and (manage) targeted business advertising.',
];